version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
      prod-dependencies:
        dependency-type: production
        update-types:
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
