services:
  lti:
    build: .
    image: scool-lti
    env_file:
      - .env
    environment:
      SCOOL_PORT: 8443
    extra_hosts:
      - "canvas.docker:10.20.95.27"
    ports:
      - "8443:8443"
    volumes:
      - ./scool:/app/scool
