services:
  lti:
    build: .
    image: scool-lti
    read_only: true
    env_file:
      - .env
    environment:
      SCOOL_PORT: 8443
    ports:
      - "8443:8443"
    volumes:
      - ./scool:/app/scool
    cpu_count: 2
    mem_limit: 2g
