services:
  scool_prod:
    build: ../
    image: scool_prod
    environment:
      SCOOL_ENV: prod
    env_file:
      - ../.env.prod
    networks:
      - scool_net_prod
    extra_hosts:
      - "canvas.docker:10.20.200.165"
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: always


networks:
  scool_net_prod:
